This notebook is for preprocessing the data and getting it ready to be clustered. This is done by exploring the data, getting rid of outliers, 
and converting data to binary to only check for presence of a feature. I chose to use a variance threshhold for some feature reduction by only 
getting rid of features where all values were identical. If a feature is just the exact same (present or not present) for every sample of data, it 
contriubutes nothing but noise. I chose not to use Principal Componenet Analysis (PCA) because it assumes the data is continuouse, not binary, causing 
potential issues due to assumptions. Multiple Correspondence Analysis (MCA) would also work for dimensionality reduction, but would likely cause a loss 
in information.

1. Load data

In [83]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import VarianceThreshold
import re
import json
from functools import reduce

In [84]:
%load_ext autoreload
%autoreload 2

import os
import sys

sys.path.insert(0, os.path.abspath(".."))
from src.utils import parquetParser, val_count, data_simplification

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [85]:
print(os.getcwd())

/Users/kennyhong/repos/StraboSpot/notebooks

In [86]:

df = parquetParser.parquet_parser(f"../data")

Running...
1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1457251 entries, 0 to 1457250
Data columns (total 475 columns):
 #    Column                                                                Dtype
---   ------                                                                -----
 0    properties_images                                                     object
 1    properties_date                                                       object
 2    properties_viewed_timestamp                                           object
 3    properties_notes                                                      object
 4    properties_orientation_data                                           object
 5    properties_modified_timestamp                                         object
 6    properties_symbology_circleColor                                      object
 7    properties_name                                                       object
 8    properties_notesTimestamp                                             object
 9    properties_time                                                       object
 10   properties_id                                                         object
 11   properties_self                                                       object
 12   geometry_type                                                         object
 13   geometry_coordinates                                                  object
 14   type                                                                  object
 15   account_email                                                         object
 16   project_id                                                            object
 17   dataset_name                                                          object
 18   properties_samples_sample_id_name                                     object
 19   properties_samples_inplaceness_of_sample                              object
 20   properties_samples_sample_notes                                       object
 21   properties_samples_oriented_sample                                    object
 22   properties_samples_id                                                 object
 23   properties_samples_main_sampling_purpose                              object
 24   properties_samples_sample_size                                        object
 25   properties_altitude                                                   object
 26   properties_altitude_accuracy                                          object
 27   properties_gps_accuracy                                               object
 28   properties_lng                                                        object
 29   properties_image_basemap                                              object
 30   properties_lat                                                        object
 31   properties_samples_sample_description                                 object
 32   properties_samples_material_type                                      object
 33   properties_samples_degree_of_weathering                               object
 34   properties_samples_label                                              object
 35   properties_samples_sample_orientation_notes                           object
 36   properties__3d_structures                                             object
 37   properties_symbology_lineColor                                        object
 38   properties_symbology_lineWidth                                        object
 39   properties_symbology_lineDasharray                                    object
 40   properties_trace_trace_feature                                        object
 41   properties_trace_trace_quality                                        object
 42   properties_trace_trace_type                                           object
 43   properties_trace_contact_type                                         object
 44   properties_trace_intrusive_contact_type                               object
 45   properties_trace_metamorphic_contact_type                             object
 46   properties_trace_trace_character                                      object
 47   properties_samples_sample_type                                        object
 48   properties_spot_radius                                                object
 49   properties_images_notes                                               object
 50   properties_sed_strat_section_strat_section_id                         object
 51   properties_sed_strat_section_column_profile                           object
 52   properties_sed_strat_section_column_y_axis_units                      object
 53   properties_sed_strat_section_purpose                                  object
 54   properties_sed_strat_section_scale_of_interest                        object
 55   properties_sed_strat_section_obs_interval_bed_obs_scale               object
 56   properties_sed_strat_section_section_type                             object
 57   properties_sed_strat_section_basin                                    object
 58   properties_sed_strat_section_age                                      object
 59   properties_sed_character                                              object
 60   properties_sed_interval_interval_thickness                            object
 61   properties_sed_interval_thickness_units                               object
 62   properties_strat_section_id                                           object
 63   properties_surface_feature_surface_feature_type                       object
 64   properties_sed_lithologies                                            object
 65   properties_sed_strat_section_total_core_length                        object
 66   properties_sed_bedding_beds                                           object
 67   geometry_geometries                                                   object
 68   properties_sed_bedding_interbed_proportion_change                     object
 69   properties_sed_bedding_interbed_proportion                            object
 70   properties_sed_bedding_lithology_at_bottom_contact                    object
 71   properties_sed_bedding_lithology_at_top_contact                       object
 72   properties_sed_bedding_package_thickness_units                        object
 73   properties_sed_strat_section_images                                   object
 74   properties_other_features                                             object
 75   properties_tephra                                                     object
 76   properties_trace_depositional_contact_type                            object
 77   properties_trace_tace_notes                                           object
 78   properties_trace_geologic_structure_type                              object
 79   properties_trace_other_feature                                        object
 80   properties_trace_other_other_feature                                  object
 81   properties_sed_fossils                                                object
 82   properties_samples_other_sampling_purpose                             object
 83   properties_symbology_fillColor                                        object
 84   properties_trace_shear_sense                                          object
 85   properties_trace_geomorphic_feature                                   object
 86   properties_trace_associated_geomorphic_feature                        object
 87   properties_trace_landscape_type                                       object
 88   properties_trace_feature_origin                                       object
 89   properties_samples_deposit_thickness                                  object
 90   properties_trace_other_structural_zones                               object
 91   properties_trace_other_other_structural_zone                          object
 92   properties_trace_other_geomorphic_feature                             object
 93   properties_trace_other_shear_sense                                    object
 94   properties_orientation_type                                           object
 95   properties_orientation_id                                             object
 96   properties_orientation_strike                                         object
 97   properties_orientation_dip_direction                                  object
 98   properties_orientation_dip                                            object
 99   properties_orientation_label                                          object
 100  properties_orientation_quality                                        object
 101  properties_orientation_feature_type                                   object
 102  properties_pet_rock_type                                              object
 103  properties_pet_igneous_rock_class                                     object
 104  properties_pet_volcanic_rock_type                                     object
 105  properties_pet_occurence_volcanic                                     object
 106  properties_trace_other_contact_type                                   object
 107  properties_trace_antropogenic_feature                                 object
 108  properties_trace_other_anthropogenic_feature                          object
 109  properties_surface_feature_other_surface_feature_type                 object
 110  properties_custom_fields_osm_id                                       object
 111  properties_trace_other_depositional_type                              object
 112  properties_custom_fields_MIN_AGE                                      object
 113  properties_custom_fields_MAX_AGE                                      object
 114  properties_trace_fold_type                                            object
 115  properties_trace_fold_attitude                                        object
 116  properties_rock_unit_unit_label_abbreviation                          object
 117  properties_pet_metamorphic_rock_type                                  object
 118  properties_sed_bedding_package_bedding_trends                         object
 119  properties_sed_structures                                             object
 120  properties_sed_interpretations                                        object
 121  properties_pet_protolith                                              object
 122  properties_pet_texture_volcanic                                       object
 123  properties_pet_alteration_volcanic                                    object
 124  properties_trace_other_trace_quality                                  object
 125  properties_sed_strat_section_section_well_name                        object
 126  properties_sed_strat_section_location_locality                        object
 127  properties_sed_strat_section_dates_of_work                            object
 128  properties_sed_strat_section_strat_section_notes                      object
 129  properties_pet_plutonic_rock_type                                     object
 130  properties_pet_occurence_plutonic                                     object
 131  properties_pet_texture_plutonic                                       object
 132  properties_pet_minerals                                               object
 133  properties_pet_other_protolith                                        object
 134  properties_pet_notes_metamorphic                                      object
 135  properties_pet_facies                                                 object
 136  properties_pet_zone                                                   object
 137  properties_fabrics                                                    object
 138  properties_pet_color_index_source_pluton                              object
 139  properties_pet_color_index_pluton                                     object
 140  properties_pet_pluton_characteristic_size_of                          object
 141  properties_pet_alteration_plutonic                                    object
 142  properties_pet_notes_plutonic                                         object
 143  properties_pet_other_texture_plutonic                                 object
 144  properties_pet_igneous                                                object
 145  properties_spot_radius_units                                          object
 146  properties_rock_unit_map_unit_name                                    object
 147  properties_rock_unit_rock_type                                        object
 148  properties_rock_unit_metamorphic_rock_types                           object
 149  properties_rock_unit_notes                                            object
 150  properties_orientation_foliation_type                                 object
 151  properties_sed_lithologies_is_this_a_bed_or_package                   object
 152  properties_sed_lithologies_primary_lithology                          object
 153  properties_sed_lithologies_thickness_units                            object
 154  properties_sed_lithologies_interval_thickness                         object
 155  properties_sed_lithologies_principal_dunham_class                     object
 156  properties_orientation_bedding_type                                   object
 157  properties_trace_trace_notes                                          object
 158  properties_orientation_trend                                          object
 159  properties_orientation_plunge                                         object
 160  properties_orientation_rake                                           object
 161  properties_orientation_rake_calculated                                object
 162  properties_rock_unit_description                                      object
 163  properties_rock_unit_sedimentary_rock_type                            object
 164  properties_sed_lithologies_notes                                      object
 165  properties_rock_unit_sediment_type                                    object
 166  properties_inferences_rosetta_outcrop                                 object
 167  properties_inferences_relationships                                   object
 168  properties_samples_longitude                                          object
 169  properties_samples_latitude                                           object
 170  properties_samples_collection_time                                    object
 171  properties_samples_collection_date                                    object
 172  properties_pet_metamorphic                                            object
 173  properties_samples_height                                             object
 174  properties_samples_width                                              object
 175  properties_samples_image_type                                         object
 176  properties_samples_caption                                            object
 177  properties_custom_fields_Station                                      object
 178  properties_custom_fields_STATNUM                                      object
 179  properties_custom_fields_VARIANT                                      object
 180  properties_custom_fields_GENERATION                                   object
 181  properties_custom_fields_FEATURE                                      object
 182  properties_custom_fields_UTMX                                         object
 183  properties_custom_fields_UTMY                                         object
 184  properties_custom_fields_Date                                         object
 185  properties_custom_fields_OBJECTID                                     object
 186  properties_custom_fields_AREA                                         object
 187  properties_custom_fields_PERIMETER                                    object
 188  properties_custom_fields_GEO_                                         object
 189  properties_custom_fields_GEO_ID                                       object
 190  properties_custom_fields_GEO_TYPE                                     object
 191  properties_custom_fields_GEO_SYM                                      object
 192  properties_custom_fields_GEO_LINK                                     object
 193  properties_custom_fields_CODE                                         object
 194  properties_custom_fields_Colour                                       object
 195  properties_custom_fields_Grouping                                     object
 196  properties_custom_fields_Shape_Leng                                   object
 197  properties_custom_fields_Shape_Area                                   object
 198  properties_custom_fields_PlateID                                      object
 199  properties_custom_fields_Terrane(s)                                   object
 200  properties_custom_fields_GEO_PAT                                      object
 201  properties_custom_fields_GEO_MISC                                     object
 202  properties_sed_strat_section_display_lithology_patterns               object
 203  properties_sed_strat_section_project_description                      object
 204  properties_sed_strat_section_how_is_section_georeferenced             object
 205  properties_samples_sample_type_1                                      object
 206  properties_samples_sample_type_2                                      object
 207  properties_samples_Sample_IGSN                                        object
 208  properties_trace_other_metamorphic_contact                            object
 209  properties_trace_other_trace_character                                object
 210  properties_orientation_facing                                         object
 211  properties_pet_metamorphic_rock_type_less_com                         object
 212  properties_sed_diagenesis                                             object
 213  properties_sed_strat_section_misc_labels                              object
 214  properties_nesting                                                    object
 215  properties_custom_fields_Orientatio                                   object
 216  properties_custom_fields_Type                                         object
 217  properties_custom_fields_MapUnit                                      object
 218  properties_sed_bedding_thickness_of_individual_beds                   object
 219  properties_sed_strat_section_what_core_repository                     object
 220  properties_sed_strat_section_type_of_corer                            object
 221  properties_sed_strat_section_depth_from_surface_to_start_of           object
 222  properties_pet_reactions                                              object
 223  properties_pet_color_index_volc                                       object
 224  properties_pet_vol_characteristic_size_of_cry                         object
 225  properties_custom_fields_year                                         object
 226  properties_custom_fields_width                                        object
 227  properties_custom_fields_color                                        object
 228  properties_pet_other_plutonic                                         object
 229  properties_pet_other_met_rocks                                        object
 230  properties_sample_id_name_samples                                     object
 231  properties_sample_description_samples                                 object
 232  properties_width_images                                               object
 233  properties_label_samples                                              object
 234  properties_id_images                                                  object
 235  properties_sample_notes_samples                                       object
 236  properties_path                                                       object

In [87]:
df.head()

,properties_images,properties_date,properties_viewed_timestamp,properties_notes,properties_orientation_data,properties_modified_timestamp,properties_symbology_circleColor,properties_name,properties_notesTimestamp,properties_time,...,properties_sed_structures_addl_mud_silt_struct,properties_orientation_unix_timestamp,properties_metamorphic,properties_sed_structures_cement_texture,properties_sed_structures_other_cement_texture,properties_sed_structures_other_addl_mud_silt_struct,properties_sed_structures_other_addl_sandstone_struct,properties_sed_structures_diversity,properties_sed_structures_behavioral_grouping,properties_sed_structures_list_of_specific_types
0,"[{""width"": 2224, ""id"": 16931574683185, ""modifi...",2023-08-27T17:25:12.000Z,1693157112029,Thick sequence of bedded chert. No sand!,"[{""id"": ""65a043ba-4177-44b3-8c8a-d4093bc4bddf""...",1693157726080,transparent,Bedded chert,Sun Aug 27 2023 10:25:41 GMT-0700 (Pacific Day...,2023-08-27T17:25:12.000Z,...,None,None,None,None,None,None,None,None,None,None
1,"[{""width"": 2448, ""id"": 16931711786083, ""modifi...",2023-08-27T20:43:07.000Z,1693168987963,"Badger creek unit includes chert argillite, li...","[{""id"": ""54169234-7ea4-463f-a6d4-a7a3115cd93e""...",1693171184906,transparent,23BCU5,Sun Aug 27 2023 14:13:29 GMT-0700 (Pacific Day...,2023-08-27T20:43:07.000Z,...,None,None,None,None,None,None,None,None,None,None
2,"[{""width"": 2224, ""id"": 16931765219731, ""modifi...",2023-08-27T22:28:21.000Z,1693175301286,Gray finely laminated possibly micrite inter l...,"[{""id"": ""9f95e7ae-e050-4606-8504-df0801870db9""...",1693176677608,transparent,23BCU6,Sun Aug 27 2023 15:51:17 GMT-0700 (Pacific Day...,2023-08-27T22:28:21.000Z,...,None,None,None,None,None,None,None,None,None,None
3,"[{""width"": 2448, ""id"": 16930789719922, ""modifi...",2023-08-26T18:31:54.000Z,1693074714285,Chert pebble breccia grades into fine sand. Si...,"[{""id"": ""b25ee609-01a4-4476-ba76-800c3151292d""...",1693089998466,transparent,23ERA4,Sat Aug 26 2023 12:03:10 GMT-0700 (Pacific Day...,2023-08-26T18:31:54.000Z,...,None,None,None,None,None,None,None,None,None,None
4,"[{""width"": 2224, ""id"": 16930050077699, ""modifi...",2023-08-25T21:56:07.000Z,1693000567149,Elk horn ridge argillite along road south of B...,None,1693009790925,transparent,23ERA1,Fri Aug 25 2023 16:34:19 GMT-0700 (Pacific Day...,2023-08-25T21:56:07.000Z,...,None,None,None,None,None,None,None,None,None,None

In [88]:
df.tail()

,properties_images,properties_date,properties_viewed_timestamp,properties_notes,properties_orientation_data,properties_modified_timestamp,properties_symbology_circleColor,properties_name,properties_notesTimestamp,properties_time,...,properties_sed_structures_addl_mud_silt_struct,properties_orientation_unix_timestamp,properties_metamorphic,properties_sed_structures_cement_texture,properties_sed_structures_other_cement_texture,properties_sed_structures_other_addl_mud_silt_struct,properties_sed_structures_other_addl_sandstone_struct,properties_sed_structures_diversity,properties_sed_structures_behavioral_grouping,properties_sed_structures_list_of_specific_types
1457246,None,2024-08-26T17:20:17+00:00,None,None,None,1724692817071,None,10458,None,2024-08-26T17:20:17+00:00,...,None,None,None,None,None,None,None,None,None,None
1457247,None,2024-08-26T17:18:00+00:00,None,None,None,1724692680599,None,7278,None,2024-08-26T17:18:00+00:00,...,None,None,None,None,None,None,None,None,None,None
1457248,None,2024-08-26T17:18:56+00:00,None,None,None,1724692736255,None,8584,None,2024-08-26T17:18:56+00:00,...,None,None,None,None,None,None,None,None,None,None
1457249,None,2024-08-26T17:17:39+00:00,None,None,None,1724692659000,None,6780,None,2024-08-26T17:17:39+00:00,...,None,None,None,None,None,None,None,None,None,None
1457250,None,2024-08-26T17:14:32+00:00,None,None,None,1724692472047,None,2328,None,2024-08-26T17:14:32+00:00,...,None,None,None,None,None,None,None,None,None,None

Some features may be unnecessary in the in analysis, especially features that pertain more to the use of the app and its features like line and circle colors for example. It is also a very necessary step to try and reduce the cardinality of the data when possible so as to reduce the noise later on and improve processing time.

In [89]:
# columns_to_drop = []
# for col in df.columns:
#     if col == "properties_orientation_modified_timestamp": # possibly indicative of purpose
#         continue 
#     elif col == "project_id":
#         continue
    
#     if re.search("^properties_symbology", col):
#         columns_to_drop.append(col)
#     if re.search("_id$", col):
#         columns_to_drop.append(col)
#     if re.search("_timestamp$", col):
#         columns_to_drop.append(col)
        
# columns_to_drop.append("properties_gps_accuracy")
# columns_to_drop.append("properties_altitude")
# columns_to_drop.append("properties_notesTimestamp")

# df = df.drop(columns= columns_to_drop)

# print("Columns Dropped:")
# for col in columns_to_drop:
#     print(f"\t{col}")

In [90]:
cols_to_drop = [
    "properties_viewed_timestamp",
	"properties_modified_timestamp",
	"properties_symbology_circleColor",
	"properties_id",
	"properties_samples_id",
	"properties_symbology_lineColor",
	"properties_symbology_lineWidth",
	"properties_symbology_lineDasharray",
	"properties_sed_strat_section_strat_section_id",
	"properties_strat_section_id",
	"properties_symbology_fillColor",
	"properties_orientation_id",
	"properties_custom_fields_osm_id",
	"properties_custom_fields_id",
	"properties_orientation_unix_timestamp",
	"properties_gps_accuracy",
	"properties_altitude",
	"properties_notesTimestamp",
]

df = df.drop(columns = cols_to_drop)

In [91]:
#getting rid of duplicates

df.drop_duplicates(inplace = True)
df.shape

(1411385, 457)

In [92]:
# drop the "properties_" part of each features name for better readability
df.columns = df.columns.str.replace('properties_', '', regex=False)
for col in df.columns:
    print(col)

images
date
notes
orientation_data
name
time
self
geometry_type
geometry_coordinates
type
account_email
project_id
dataset_name
samples_sample_id_name
samples_inplaceness_of_sample
samples_sample_notes
samples_oriented_sample
samples_main_sampling_purpose
samples_sample_size
altitude_accuracy
lng
image_basemap
lat
samples_sample_description
samples_material_type
samples_degree_of_weathering
samples_label
samples_sample_orientation_notes
_3d_structures
trace_trace_feature
trace_trace_quality
trace_trace_type
trace_contact_type
trace_intrusive_contact_type
trace_metamorphic_contact_type
trace_trace_character
samples_sample_type
spot_radius
images_notes
sed_strat_section_column_profile
sed_strat_section_column_y_axis_units
sed_strat_section_purpose
sed_strat_section_scale_of_interest
sed_strat_section_obs_interval_bed_obs_scale
sed_strat_section_section_type
sed_strat_section_basin
sed_strat_section_age
sed_character
sed_interval_interval_thickness
sed_interval_thickness_units
surface_feature_surface_feature_type
sed_lithologies
sed_strat_section_total_core_length
sed_bedding_beds
geometry_geometries
sed_bedding_interbed_proportion_change
sed_bedding_interbed_proportion
sed_bedding_lithology_at_bottom_contact
sed_bedding_lithology_at_top_contact
sed_bedding_package_thickness_units
sed_strat_section_images
other_features
tephra
trace_depositional_contact_type
trace_tace_notes
trace_geologic_structure_type
trace_other_feature
trace_other_other_feature
sed_fossils
samples_other_sampling_purpose
trace_shear_sense
trace_geomorphic_feature
trace_associated_geomorphic_feature
trace_landscape_type
trace_feature_origin
samples_deposit_thickness
trace_other_structural_zones
trace_other_other_structural_zone
trace_other_geomorphic_feature
trace_other_shear_sense
orientation_type
orientation_strike
orientation_dip_direction
orientation_dip
orientation_label
orientation_quality
orientation_feature_type
pet_rock_type
pet_igneous_rock_class
pet_volcanic_rock_type
pet_occurence_volcanic
trace_other_contact_type
trace_antropogenic_feature
trace_other_anthropogenic_feature
surface_feature_other_surface_feature_type
trace_other_depositional_type
custom_fields_MIN_AGE
custom_fields_MAX_AGE
trace_fold_type
trace_fold_attitude
rock_unit_unit_label_abbreviation
pet_metamorphic_rock_type
sed_bedding_package_bedding_trends
sed_structures
sed_interpretations
pet_protolith
pet_texture_volcanic
pet_alteration_volcanic
trace_other_trace_quality
sed_strat_section_section_well_name
sed_strat_section_location_locality
sed_strat_section_dates_of_work
sed_strat_section_strat_section_notes
pet_plutonic_rock_type
pet_occurence_plutonic
pet_texture_plutonic
pet_minerals
pet_other_protolith
pet_notes_metamorphic
pet_facies
pet_zone
fabrics
pet_color_index_source_pluton
pet_color_index_pluton
pet_pluton_characteristic_size_of
pet_alteration_plutonic
pet_notes_plutonic
pet_other_texture_plutonic
pet_igneous
spot_radius_units
rock_unit_map_unit_name
rock_unit_rock_type
rock_unit_metamorphic_rock_types
rock_unit_notes
orientation_foliation_type
sed_lithologies_is_this_a_bed_or_package
sed_lithologies_primary_lithology
sed_lithologies_thickness_units
sed_lithologies_interval_thickness
sed_lithologies_principal_dunham_class
orientation_bedding_type
trace_trace_notes
orientation_trend
orientation_plunge
orientation_rake
orientation_rake_calculated
rock_unit_description
rock_unit_sedimentary_rock_type
sed_lithologies_notes
rock_unit_sediment_type
inferences_rosetta_outcrop
inferences_relationships
samples_longitude
samples_latitude
samples_collection_time
samples_collection_date
pet_metamorphic
samples_height
samples_width
samples_image_type
samples_caption
custom_fields_Station
custom_fields_STATNUM
custom_fields_VARIANT
custom_fields_GENERATION
custom_fields_FEATURE
custom_fields_UTMX
custom_fields_UTMY
custom_fields_Date
custom_fields_OBJECTID
custom_fields_AREA
custom_fields_PERIMETER
custom_fields_GEO_
custom_fields_GEO_ID
custom_fields_GEO_TYPE
custom_fields_GEO_SYM
custom_fields_GEO_LINK
custom_fields_CODE
custom_fields_Colour
custom_fields_Grouping
custom_fields_Shape_Leng
custom_fields_Shape_Area
custom_fields_PlateID
custom_fields_Terrane(s)
custom_fields_GEO_PAT
custom_fields_GEO_MISC
sed_strat_section_display_lithology_patterns
sed_strat_section_project_description
sed_strat_section_how_is_section_georeferenced
samples_sample_type_1
samples_sample_type_2
samples_Sample_IGSN
trace_other_metamorphic_contact
trace_other_trace_character
orientation_facing
pet_metamorphic_rock_type_less_com
sed_diagenesis
sed_strat_section_misc_labels
nesting
custom_fields_Orientatio
custom_fields_Type
custom_fields_MapUnit
sed_bedding_thickness_of_individual_beds
sed_strat_section_what_core_repository
sed_strat_section_type_of_corer
sed_strat_section_depth_from_surface_to_start_of
pet_reactions
pet_color_index_volc
pet_vol_characteristic_size_of_cry
custom_fields_year
custom_fields_width
custom_fields_color
pet_other_plutonic
pet_other_met_rocks
sample_id_name_samples
sample_description_samples
width_images
label_samples
id_images
sample_notes_samples
path
image_type_images
height_images
self_images
annotated_images
caption_images
main_sampling_purpose_samples
sample_type_samples
title_images
material_type_samples
id_samples
sample_size_samples
SpotID
orientation_movement
orientation_vein_fill
data_tables
custom_fields_Foto
custom_fields_Odber
custom_fields_auxiliary_
custom_fields_auxiliar_1
orientation_fault_or_sz_type
orientation_movement_justification
orientation_directional_indicators
orientation_associated_orientation
orientation_notes
custom_fields_layer
custom_fields_path
custom_fields_name
custom_fields_self
custom_fields_geometry
custom_fields_latitude
custom_fields_longitude
custom_fields_altitude(m
orientation_modified_timestamp
sed_lithologies_principal_siliciclastic_type
sed_lithologies_interbed_lithology
sed_lithologies_interbed_siliciclastic_type
sed_lithologies_primary_lithology_thickness
sed_lithologies_interbed_thickness
sed_lithologies_interbed_proportion_change
sed_lithologies_interbed_thickness_change
sed_lithologies_sand_principal_grain_size
sed_lithologies_mud_silt_interbed_grain_size
sed_lithologies_interbed_proportion
sed_lithologies_sandstone_prin_struct
sed_interpretations_clastic
sed_interpretations_shallow_marine_clastic_environ
sed_interpretations_general
sed_structures_sandstone_structures
sed_structures_sandstone_prin_struct
sed_structures_bioturbation
sed_structures_bioturbation_index
sed_lithologies_stratification
sed_lithologies_character_of_lower_contacts
sed_lithologies_mud_silt_principal_grain_size
sed_lithologies_grain_size
sed_structures_biogenic_growth_structures
sed_structures_internal_bedding_struct
sed_lithologies_laminae_thickness_i_select_more_than_one
sed_lithologies_lithification
sed_lithologies_sorting
sed_lithologies_sand_interbed_grain_size
sed_structures_descriptive
sed_lithologies_package_geometry
sed_lithologies_bedding_thickness
sed_structures_deformation_structures
sed_lithologies_secondary_lithologies
sed_lithologies_carbonate_components
sed_structures_fabric_selective
sed_structures_skeletal_fossil
sed_structures_mollusca
sed_structures_addl_sandstone_struct
sed_structures_cross_stratified_types
sed_lithologies_color_appearance
sed_lithologies_gypsum_anhydrite_diagenetic_type
sed_structures_dominant_component
sed_structures_microbial_reef_or_skelatal_mic
sed_lithologies_other_dunham_components
sed_lithologies_wackestone_percent
sed_structures_chemogenic_structures_type
sed_structures_cement_composition
sed_lithologies_evaporite_type
sed_lithologies_relative_resistance_weathering
sed_lithologies_minerals_present
sed_structures_limestone_structures
sed_interpretations_carbonates
sed_interpretations_sediment_transport
sed_interpretations_eolian_environments
sed_interpretations_geometry
sed_lithologies_shape_of_lower_contacts
sed_lithologies_bedding_character
sed_lithologies_character_of_upper_contacts
sed_structures_asymmetric_height
custom_fields_tipo
custom_fields_ latitude
custom_fields_ longitude
custom_fields_ horiz_pre
custom_fields_ vert_prec
custom_fields_ declinati
custom_fields_ timedate
custom_fields_SHAPE_Leng
custom_fields_SHAPE_Area
custom_fields_IsConceale
custom_fields_LocationCo
custom_fields_ExistenceC
custom_fields_IdentityCo
custom_fields_DataSource
samples_color
pet_other_volcanic_rocks
custom_fields_Point
custom_fields_Northings
custom_fields_Eastings
custom_fields_Note
pet_fault
custom_fields_Date_Time
trace_marker_layer_details
trace_other_intrusive_contact
pet_other_occurence_plutonic
sed_lithologies_volcaniclastic_type
sed_lithologies_other_volcaniclastic_type
sed_lithologies_fresh_color
sed_lithologies_weathered_color
sed_lithologies_sand_medium_lower_percent
sed_lithologies_sand_very_coarse_percent
sed_lithologies_maximum_clast_size_cm
sed_lithologies_minimum_clast_size_cm
sed_lithologies_matrix_size
sed_lithologies_character
sed_lithologies_bedding_grain_size_trends
sed_lithologies_bedding_grain_size_trend_description
sed_lithologies_package_grain_size_trends
sed_lithologies_shape
sed_lithologies_rounding
sed_lithologies_package_lateral_extent
sed_lithologies_shape_of_lower_conta_select_more_than_one
sed_lithologies_character_of_lower_c_select_more_than_one
sed_lithologies_lower_contact_relief
sed_lithologies_character_of_upper_c_select_more_than_one
sed_lithologies_upper_contact_relief
sed_lithologies_granule_percent
sed_lithologies_average_clast_size_cm
sed_lithologies_package_grain_size_trend_description
sed_lithologies_glass_percent
sed_lithologies_package_bedding_trends
sed_lithologies_shape_of_upper_conta_select_more_than_one
sed_lithologies_sand_very_fine_percent
sed_lithologies_silt_percent
sed_lithologies_ignimbrite_percent
samples_other_material_type
custom_fields_fid
custom_fields_ELEV
custom_fields_Contacto
pet_notes_volcanic
pet_structure_volcanic
pet_color_index_source_volc
custom_fields_GFP_TYPE
orientation_facing_defined_by
pet_other_modification_plutonic
pet_alteration_or
custom_fields_Bot
custom_fields_GM_TYPE
custom_fields_quality
custom_fields_type
sed_lithologies_congl_principal_grain_size
custom_fields_UNITLABEL
custom_fields_ID_FUENTE
sed_lithologies_mud_percent
sed_lithologies_dunham_class
samples_other_sample_type_2
samples_sample_unit
custom_fields_area
custom_fields_StationID
custom_fields_RuleID
sed_interpretations_modifier
sed_interpretations_lithology
sed_interpretations_energy
sed_interpretations_notes
sed_lithologies_siliciclastic_lithologies
sed_lithologies_interbed_dunham_class
sed_lithologies_sandstone_classification
sed_lithologies_sandstone_type_dott
sed_structures_vein_composition
sed_lithologies_mud_silt_prin_struct
sed_structures_all_physical_struct_notes
sed_structures_breccia_structures
sed_structures_bedding_plane_features
sed_structures_bedform_type
sed_structures_burrow_fill_type
sed_interpretations_type
sed_interpretations_general_surfaces
sed_interpretations_sequence_stratigraphic_surfaces
sed_structures_mudstone_structures
sed_structures_nodules_concretions_comp
sed_structures_carbonate_desiccation_and_diss
sed_structures_nodules_concretions_size
sed_structures_paleosol_horizons
sed_structures_paleosol_structures
sed_interpretations_miscellaneous
sed_structures_addl_limestone_dolomite_struct
sed_structures_limestone_dolomite_prin_struct
sed_lithologies_limestone_dolomite_prin_struct
sed_interpretations_carbonate
sed_interpretations_lake_subenvironments
sed_interpretations_tectonic_setting
sed_interpretations_relief
sed_interpretations_relief_scale
sed_interpretations_extent
sed_interpretations_extent_scale
sed_interpretations_description
rock_unit_era
rock_unit_period
rock_unit_epoch
rock_unit_group_unit_type
custom_fields_rock_type
custom_fields_rock_class
custom_fields_absolute_a
custom_fields_TYPE
custom_fields_Name
pet_other_occurance_volcanic
sed_lithologies_lamination_character_select_more_than_one
minerals
data_urls
sed_interpretations_fluvial_architectural_elements
sed_interpretations_other_fluvial_element
sed_structures_mud_silt_prin_struct
sed_structures_sandstone_struct_notes
sed_structures_faunal_assemblage
sed_strat_section_other_purpose
sed_structures_addl_mud_silt_struct
metamorphic
sed_structures_cement_texture
sed_structures_other_cement_texture
sed_structures_other_addl_mud_silt_struct
sed_structures_other_addl_sandstone_struct
sed_structures_diversity
sed_structures_behavioral_grouping
sed_structures_list_of_specific_types

2. Explore features and properly split/encode them

In [93]:
# images seems to contain a dictionary for that contain metadata per picture. 
# I will split the "images" feature up to properly reflect this. I will exclude the "widgth", "height", "id", "timestamp", and "self" 
df[["images"]].value_counts().tail(5)

images
[{"width": 2448, "id": 16261273630552, "modified_timestamp": "1631562787942", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261273630552"}, {"width": 2448, "id": 16261273570267, "modified_timestamp": "1631562785810", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261273570267"}]                                                                                                                                                                                                                                               1
[{"width": 2448, "id": 16261274028364, "modified_timestamp": "1627060244522", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261274028364"}, {"width": 2448, "id": 16261274115612, "modified_timestamp": "1627060245519", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261274115612"}, {"width": 2448, "caption": "21CR42", "id": 16261283923180, "title": "21CR42", "modified_timestamp": "1627060246757", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261283923180"}]    1
[{"width": 2448, "id": 16261275741534, "modified_timestamp": "1626536255237", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261275741534"}, {"width": 2448, "id": 16261273475506, "modified_timestamp": "1626536151744", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261273475506"}]                                                                                                                                                                                                                                               1
[{"width": 2448, "id": 16261278063902, "modified_timestamp": "1626535790812", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261278063902"}, {"width": 2448, "id": 16261277939956, "modified_timestamp": "1626535757235", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16261277939956"}]                                                                                                                                                                                                                                               1
[{"width": 999, "id": 16529031070376, "title": "Wheeler diagram", "modified_timestamp": "", "height": 1076, "image_type": "sketch", "annotated": false, "self": "https://strabospot.org/db/image/16529031070376"}, {"width": 1000, "id": 16529030963524, "title": "Two sections on outcrop sketch", "modified_timestamp": "", "image_type": "sketch", "height": 1335, "annotated": false, "self": "https://strabospot.org/db/image/16529030963524"}]                                                                                                                                                                                                 1
Name: count, dtype: int64

In [ ]:
keys_to_drop = ["width", "height", "id", "modified_timestamp", "self" ]
rows = []
for row in df[["images"]].itertuples():
        # reads the turns the json values in "images" into a python list
        try:
            images_list = json.loads(row.images)
            # print(images_list)
        except:
            rows.append({})
            continue
        
        # appends images_ prefix and drops unwanted keys
        for i, images in enumerate(images_list):
            images_list[i] = {
                f"images_{key}": value
                for key, value in images.items()
                if key not in keys_to_drop
        }
        
        
        if len(images_list) > 1:
            # Keep the first dict's keys unchanged; append a sequential suffix
            # (_2, _3, ...) to the keys of the remaining dicts
            images_list = [
                d if k == 0 else {f"{key}_{k+1}": value for key, value in d.items()}
                for k, d in enumerate(images_list)
            ]
            
        if not images_list:
            rows.append({})
            continue

        # joins all images into a single dict
        new_images = reduce(lambda x, y: x | y, images_list)
        rows.append(new_images)     
        # print(new_images)
        
images_df = pd.DataFrame(rows, df.index)  
df = pd.concat([df, images_df], axis = 1)

:

In [79]:
print(df.filter(like = "images").head().to_markdown())

|    | images                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | images_notes   | sed_strat_section_images   | width_images   | id_images   | image_type_images   | height_images   | self_images   | annotated_images   | caption_images   | title_images   |
|---:|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:---------------|:---------------------------|:---------------|:------------|:--------------------|:----------------|:--------------|:-------------------|:-----------------|:---------------|
|  0 | [{"width": 2224, "id": 16931574683185, "modified_timestamp": "1693697410352", "image_type": "sketch", "height": 1348, "annotated": false, "self": "https://strabospot.org/db/image/16931574683185"}, {"width": 2224, "id": 16931574679863, "modified_timestamp": "1693697404659", "image_type": "sketch", "height": 1348, "annotated": false, "self": "https://strabospot.org/db/image/16931574679863"}, {"width": 2448, "id": 16931573631716, "modified_timestamp": "1693697408510", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931573631716"}, {"width": 2448, "id": 16931573535138, "modified_timestamp": "1693697397195", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931573535138"}, {"width": 2448, "id": 16931573190640, "modified_timestamp": "1693697406418", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931573190640"}, {"width": 3264, "id": 16931572958870, "modified_timestamp": "1693697402474", "height": 2448, "annotated": false, "self": "https://strabospot.org/db/image/16931572958870"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                |                            |                |             |                     |                 |               |                    |                  |                |
|  1 | [{"width": 2448, "id": 16931711786083, "modified_timestamp": "1693697433415", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931711786083"}, {"width": 2448, "id": 16931711703220, "modified_timestamp": "1693697431563", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931711703220"}, {"width": 1836, "id": 16931711458897, "modified_timestamp": "1693697422381", "height": 2448, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931711458897"}, {"width": 3264, "id": 16931711224456, "modified_timestamp": "1693697429328", "height": 2448, "annotated": false, "self": "https://strabospot.org/db/image/16931711224456"}, {"width": 2448, "id": 16931695856402, "modified_timestamp": "1693697412407", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931695856402"}, {"width": 1836, "id": 16931695637488, "modified_timestamp": "1693697417062", "height": 2448, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931695637488"}, {"width": 1836, "id": 16931695330263, "modified_timestamp": "1693697414135", "height": 2448, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931695330263"}, {"width": 1836, "id": 16931695268307, "modified_timestamp": "1693697419839", "height": 2448, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931695268307"}, {"width": 2448, "id": 16931695149721, "modified_timestamp": "1693697415722", "height": 3264, "annotated": false, "self": "https://strabospot.org/db/image/16931695149721"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                |                            |                |             |                     |                 |               |                    |                  |                |
|  2 | [{"width": 2224, "id": 16931765219731, "modified_timestamp": "1693697449009", "image_type": "sketch", "height": 1348, "annotated": false, "self": "https://strabospot.org/db/image/16931765219731"}, {"width": 2448, "id": 16931764652399, "modified_timestamp": "1693697446062", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931764652399"}, {"width": 2448, "id": 16931764605554, "modified_timestamp": "1693697440354", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931764605554"}, {"width": 3264, "id": 16931764485761, "modified_timestamp": "1693697437605", "height": 2448, "annotated": false, "self": "https://strabospot.org/db/image/16931764485761"}, {"width": 2224, "id": 16931758044403, "modified_timestamp": "1693697442531", "image_type": "sketch", "height": 1348, "annotated": false, "self": "https://strabospot.org/db/image/16931758044403"}, {"width": 2224, "id": 16931757598450, "modified_timestamp": "1693697444200", "image_type": "sketch", "height": 1348, "annotated": false, "self": "https://strabospot.org/db/image/16931757598450"}, {"width": 2448, "id": 16931757195693, "modified_timestamp": "1693697435537", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931757195693"}, {"width": 2448, "id": 16931757143331, "modified_timestamp": "1693697424763", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931757143331"}, {"width": 2448, "id": 16931756701806, "modified_timestamp": "1693697427020", "height": 1836, "image_type": "photo", "annotated": false, "self": "https://strabospot.org/db/image/16931756701806"}]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                |                            |                |             |                     |                 |               |                    |                  |                |

In [81]:
print(df.columns)

Index(['images', 'date', 'notes', 'orientation_data', 'name', 'time', 'self',
       'geometry_type', 'geometry_coordinates', 'type',
       ...
       'feature_id', 'spotId', 'timestamp', 'image_category',
       'field_image_type', 'plates', 'other_micrograph_image_type',
       'polarizer', 'type_of_light', 'src'],
      dtype='object', length=489)

In [44]:
df["images_annotated"].value_counts()

images_annotated
False    1
Name: count, dtype: int64

In [34]:
# uses variance threshold for feature reduction, removes features where all values are identical

selector = VarianceThreshold(threshold=0) #removes all features with low variance in 100% of samples  (you do (1 - percentage of same values) * percentage of vaues that are the same)
selector.fit_transform(df)

cols_idxs = selector.get_support(indices=True)
df = df.iloc[:,cols_idxs]

print(df.shape)
# val_count(df)

(1411385, 433)

In [35]:
for columns in df.columns:
    print(columns)

project_id
properties_images
properties_notes
properties_orientation_data
properties_name
geometry_type
geometry_coordinates
dataset_name
properties_samples_sample_id_name
properties_samples_inplaceness_of_sample
properties_samples_sample_notes
properties_samples_oriented_sample
properties_samples_main_sampling_purpose
properties_samples_sample_size
properties_altitude_accuracy
properties_lng
properties_image_basemap
properties_lat
properties_samples_sample_description
properties_samples_material_type
properties_samples_degree_of_weathering
properties_samples_label
properties_samples_sample_orientation_notes
properties__3d_structures
properties_trace_trace_feature
properties_trace_trace_quality
properties_trace_trace_type
properties_trace_contact_type
properties_trace_intrusive_contact_type
properties_trace_metamorphic_contact_type
properties_trace_trace_character
properties_samples_sample_type
properties_spot_radius
properties_images_notes
properties_sed_strat_section_column_profile
properties_sed_strat_section_column_y_axis_units
properties_sed_strat_section_purpose
properties_sed_strat_section_scale_of_interest
properties_sed_strat_section_obs_interval_bed_obs_scale
properties_sed_strat_section_section_type
properties_sed_strat_section_basin
properties_sed_strat_section_age
properties_sed_character
properties_sed_interval_interval_thickness
properties_sed_interval_thickness_units
properties_surface_feature_surface_feature_type
properties_sed_lithologies
properties_sed_strat_section_total_core_length
properties_sed_bedding_beds
geometry_geometries
properties_sed_bedding_interbed_proportion_change
properties_sed_bedding_interbed_proportion
properties_sed_bedding_lithology_at_bottom_contact
properties_sed_bedding_lithology_at_top_contact
properties_sed_bedding_package_thickness_units
properties_sed_strat_section_images
properties_other_features
properties_tephra
properties_trace_depositional_contact_type
properties_trace_tace_notes
properties_trace_geologic_structure_type
properties_trace_other_feature
properties_trace_other_other_feature
properties_sed_fossils
properties_samples_other_sampling_purpose
properties_trace_shear_sense
properties_trace_geomorphic_feature
properties_trace_associated_geomorphic_feature
properties_trace_landscape_type
properties_trace_feature_origin
properties_samples_deposit_thickness
properties_trace_other_structural_zones
properties_trace_other_other_structural_zone
properties_trace_other_geomorphic_feature
properties_trace_other_shear_sense
properties_orientation_type
properties_orientation_strike
properties_orientation_dip_direction
properties_orientation_dip
properties_orientation_label
properties_orientation_quality
properties_orientation_feature_type
properties_pet_rock_type
properties_pet_igneous_rock_class
properties_pet_volcanic_rock_type
properties_pet_occurence_volcanic
properties_trace_other_contact_type
properties_trace_antropogenic_feature
properties_trace_other_anthropogenic_feature
properties_surface_feature_other_surface_feature_type
properties_trace_other_depositional_type
properties_custom_fields_MIN_AGE
properties_custom_fields_MAX_AGE
properties_trace_fold_type
properties_trace_fold_attitude
properties_rock_unit_unit_label_abbreviation
properties_pet_metamorphic_rock_type
properties_sed_bedding_package_bedding_trends
properties_sed_structures
properties_sed_interpretations
properties_pet_protolith
properties_pet_texture_volcanic
properties_pet_alteration_volcanic
properties_trace_other_trace_quality
properties_sed_strat_section_section_well_name
properties_sed_strat_section_location_locality
properties_sed_strat_section_dates_of_work
properties_sed_strat_section_strat_section_notes
properties_pet_plutonic_rock_type
properties_pet_occurence_plutonic
properties_pet_texture_plutonic
properties_pet_minerals
properties_pet_other_protolith
properties_pet_notes_metamorphic
properties_pet_facies
properties_pet_zone
properties_fabrics
properties_pet_color_index_source_pluton
properties_pet_color_index_pluton
properties_pet_pluton_characteristic_size_of
properties_pet_alteration_plutonic
properties_pet_notes_plutonic
properties_pet_other_texture_plutonic
properties_pet_igneous
properties_spot_radius_units
properties_rock_unit_map_unit_name
properties_rock_unit_rock_type
properties_rock_unit_metamorphic_rock_types
properties_rock_unit_notes
properties_orientation_foliation_type
properties_sed_lithologies_is_this_a_bed_or_package
properties_sed_lithologies_primary_lithology
properties_sed_lithologies_thickness_units
properties_sed_lithologies_interval_thickness
properties_sed_lithologies_principal_dunham_class
properties_orientation_bedding_type
properties_trace_trace_notes
properties_orientation_trend
properties_orientation_plunge
properties_orientation_rake
properties_orientation_rake_calculated
properties_rock_unit_description
properties_rock_unit_sedimentary_rock_type
properties_sed_lithologies_notes
properties_rock_unit_sediment_type
properties_inferences_rosetta_outcrop
properties_inferences_relationships
properties_samples_longitude
properties_samples_latitude
properties_samples_collection_time
properties_samples_collection_date
properties_pet_metamorphic
properties_samples_height
properties_samples_width
properties_samples_image_type
properties_samples_caption
properties_custom_fields_Station
properties_custom_fields_STATNUM
properties_custom_fields_VARIANT
properties_custom_fields_GENERATION
properties_custom_fields_FEATURE
properties_custom_fields_UTMX
properties_custom_fields_UTMY
properties_custom_fields_Date
properties_custom_fields_OBJECTID
properties_custom_fields_AREA
properties_custom_fields_PERIMETER
properties_custom_fields_GEO_
properties_custom_fields_GEO_ID
properties_custom_fields_GEO_TYPE
properties_custom_fields_GEO_SYM
properties_custom_fields_GEO_LINK
properties_custom_fields_CODE
properties_custom_fields_Colour
properties_custom_fields_Grouping
properties_custom_fields_Shape_Leng
properties_custom_fields_Shape_Area
properties_custom_fields_PlateID
properties_custom_fields_Terrane(s)
properties_custom_fields_GEO_PAT
properties_custom_fields_GEO_MISC
properties_sed_strat_section_display_lithology_patterns
properties_sed_strat_section_project_description
properties_sed_strat_section_how_is_section_georeferenced
properties_samples_sample_type_1
properties_samples_sample_type_2
properties_samples_Sample_IGSN
properties_trace_other_metamorphic_contact
properties_trace_other_trace_character
properties_orientation_facing
properties_pet_metamorphic_rock_type_less_com
properties_sed_diagenesis
properties_sed_strat_section_misc_labels
properties_nesting
properties_custom_fields_Orientatio
properties_custom_fields_Type
properties_custom_fields_MapUnit
properties_sed_bedding_thickness_of_individual_beds
properties_sed_strat_section_what_core_repository
properties_sed_strat_section_type_of_corer
properties_sed_strat_section_depth_from_surface_to_start_of
properties_pet_reactions
properties_pet_color_index_volc
properties_pet_vol_characteristic_size_of_cry
properties_custom_fields_year
properties_custom_fields_width
properties_custom_fields_color
properties_pet_other_plutonic
properties_pet_other_met_rocks
properties_orientation_movement
properties_orientation_vein_fill
properties_data_tables
properties_custom_fields_Foto
properties_custom_fields_Odber
properties_custom_fields_auxiliary_
properties_custom_fields_auxiliar_1
properties_orientation_fault_or_sz_type
properties_orientation_movement_justification
properties_orientation_directional_indicators
properties_orientation_associated_orientation
properties_orientation_notes
properties_custom_fields_layer
properties_custom_fields_path
properties_custom_fields_name
properties_custom_fields_self
properties_custom_fields_geometry
properties_custom_fields_latitude
properties_custom_fields_longitude
properties_custom_fields_altitude(m
properties_orientation_modified_timestamp
properties_sed_lithologies_principal_siliciclastic_type
properties_sed_lithologies_interbed_lithology
properties_sed_lithologies_interbed_siliciclastic_type
properties_sed_lithologies_primary_lithology_thickness
properties_sed_lithologies_interbed_thickness
properties_sed_lithologies_interbed_proportion_change
properties_sed_lithologies_interbed_thickness_change
properties_sed_lithologies_sand_principal_grain_size
properties_sed_lithologies_mud_silt_interbed_grain_size
properties_sed_lithologies_interbed_proportion
properties_sed_lithologies_sandstone_prin_struct
properties_sed_interpretations_clastic
properties_sed_interpretations_shallow_marine_clastic_environ
properties_sed_interpretations_general
properties_sed_structures_sandstone_structures
properties_sed_structures_sandstone_prin_struct
properties_sed_structures_bioturbation
properties_sed_structures_bioturbation_index
properties_sed_lithologies_stratification
properties_sed_lithologies_character_of_lower_contacts
properties_sed_lithologies_mud_silt_principal_grain_size
properties_sed_lithologies_grain_size
properties_sed_structures_biogenic_growth_structures
properties_sed_structures_internal_bedding_struct
properties_sed_lithologies_laminae_thickness_i_select_more_than_one
properties_sed_lithologies_lithification
properties_sed_lithologies_sorting
properties_sed_lithologies_sand_interbed_grain_size
properties_sed_structures_descriptive
properties_sed_lithologies_package_geometry
properties_sed_lithologies_bedding_thickness
properties_sed_structures_deformation_structures
properties_sed_lithologies_secondary_lithologies
properties_sed_lithologies_carbonate_components
properties_sed_structures_fabric_selective
properties_sed_structures_skeletal_fossil
properties_sed_structures_mollusca
properties_sed_structures_addl_sandstone_struct
properties_sed_structures_cross_stratified_types
properties_sed_lithologies_color_appearance
properties_sed_lithologies_gypsum_anhydrite_diagenetic_type
properties_sed_structures_dominant_component
properties_sed_structures_microbial_reef_or_skelatal_mic
properties_sed_lithologies_other_dunham_components
properties_sed_lithologies_wackestone_percent
properties_sed_structures_chemogenic_structures_type
properties_sed_structures_cement_composition
properties_sed_lithologies_evaporite_type
properties_sed_lithologies_relative_resistance_weathering
properties_sed_lithologies_minerals_present
properties_sed_structures_limestone_structures
properties_sed_interpretations_carbonates
properties_sed_interpretations_sediment_transport
properties_sed_interpretations_eolian_environments
properties_sed_interpretations_geometry
properties_sed_lithologies_shape_of_lower_contacts
properties_sed_lithologies_bedding_character
properties_sed_lithologies_character_of_upper_contacts
properties_sed_structures_asymmetric_height
properties_custom_fields_tipo
properties_custom_fields_ latitude
properties_custom_fields_ longitude
properties_custom_fields_ horiz_pre
properties_custom_fields_ vert_prec
properties_custom_fields_ declinati
properties_custom_fields_ timedate
properties_custom_fields_SHAPE_Leng
properties_custom_fields_SHAPE_Area
properties_custom_fields_IsConceale
properties_custom_fields_LocationCo
properties_custom_fields_ExistenceC
properties_custom_fields_IdentityCo
properties_custom_fields_DataSource
properties_samples_color
properties_pet_other_volcanic_rocks
properties_custom_fields_Point
properties_custom_fields_Northings
properties_custom_fields_Eastings
properties_custom_fields_Note
properties_pet_fault
properties_custom_fields_Date_Time
properties_trace_marker_layer_details
properties_trace_other_intrusive_contact
properties_pet_other_occurence_plutonic
properties_sed_lithologies_volcaniclastic_type
properties_sed_lithologies_other_volcaniclastic_type
properties_sed_lithologies_fresh_color
properties_sed_lithologies_weathered_color
properties_sed_lithologies_sand_medium_lower_percent
properties_sed_lithologies_sand_very_coarse_percent
properties_sed_lithologies_maximum_clast_size_cm
properties_sed_lithologies_minimum_clast_size_cm
properties_sed_lithologies_matrix_size
properties_sed_lithologies_character
properties_sed_lithologies_bedding_grain_size_trends
properties_sed_lithologies_bedding_grain_size_trend_description
properties_sed_lithologies_package_grain_size_trends
properties_sed_lithologies_shape
properties_sed_lithologies_rounding
properties_sed_lithologies_package_lateral_extent
properties_sed_lithologies_shape_of_lower_conta_select_more_than_one
properties_sed_lithologies_character_of_lower_c_select_more_than_one
properties_sed_lithologies_lower_contact_relief
properties_sed_lithologies_character_of_upper_c_select_more_than_one
properties_sed_lithologies_upper_contact_relief
properties_sed_lithologies_granule_percent
properties_sed_lithologies_average_clast_size_cm
properties_sed_lithologies_package_grain_size_trend_description
properties_sed_lithologies_glass_percent
properties_sed_lithologies_package_bedding_trends
properties_sed_lithologies_shape_of_upper_conta_select_more_than_one
properties_sed_lithologies_sand_very_fine_percent
properties_sed_lithologies_silt_percent
properties_sed_lithologies_ignimbrite_percent
properties_samples_other_material_type
properties_custom_fields_fid
properties_custom_fields_ELEV
properties_custom_fields_Contacto
properties_pet_notes_volcanic
properties_pet_structure_volcanic
properties_pet_color_index_source_volc
properties_custom_fields_GFP_TYPE
properties_orientation_facing_defined_by
properties_pet_other_modification_plutonic
properties_pet_alteration_or
properties_custom_fields_Bot
properties_custom_fields_GM_TYPE
properties_custom_fields_quality
properties_custom_fields_type
properties_sed_lithologies_congl_principal_grain_size
properties_custom_fields_UNITLABEL
properties_custom_fields_ID_FUENTE
properties_sed_lithologies_mud_percent
properties_sed_lithologies_dunham_class
properties_samples_other_sample_type_2
properties_samples_sample_unit
properties_custom_fields_area
properties_custom_fields_StationID
properties_custom_fields_RuleID
properties_sed_interpretations_modifier
properties_sed_interpretations_lithology
properties_sed_interpretations_energy
properties_sed_interpretations_notes
properties_sed_lithologies_siliciclastic_lithologies
properties_sed_lithologies_interbed_dunham_class
properties_sed_lithologies_sandstone_classification
properties_sed_lithologies_sandstone_type_dott
properties_sed_structures_vein_composition
properties_sed_lithologies_mud_silt_prin_struct
properties_sed_structures_all_physical_struct_notes
properties_sed_structures_breccia_structures
properties_sed_structures_bedding_plane_features
properties_sed_structures_bedform_type
properties_sed_structures_burrow_fill_type
properties_sed_interpretations_type
properties_sed_interpretations_general_surfaces
properties_sed_interpretations_sequence_stratigraphic_surfaces
properties_sed_structures_mudstone_structures
properties_sed_structures_nodules_concretions_comp
properties_sed_structures_carbonate_desiccation_and_diss
properties_sed_structures_nodules_concretions_size
properties_sed_structures_paleosol_horizons
properties_sed_structures_paleosol_structures
properties_sed_interpretations_miscellaneous
properties_sed_structures_addl_limestone_dolomite_struct
properties_sed_structures_limestone_dolomite_prin_struct
properties_sed_lithologies_limestone_dolomite_prin_struct
properties_sed_interpretations_carbonate
properties_sed_interpretations_lake_subenvironments
properties_sed_interpretations_tectonic_setting
properties_sed_interpretations_relief
properties_sed_interpretations_relief_scale
properties_sed_interpretations_extent
properties_sed_interpretations_extent_scale
properties_sed_interpretations_description
properties_rock_unit_era
properties_rock_unit_period
properties_rock_unit_epoch
properties_rock_unit_group_unit_type
properties_custom_fields_rock_type
properties_custom_fields_rock_class
properties_custom_fields_absolute_a
properties_custom_fields_TYPE
properties_custom_fields_Name
properties_pet_other_occurance_volcanic
properties_sed_lithologies_lamination_character_select_more_than_one
properties_minerals
properties_data_urls
properties_sed_interpretations_fluvial_architectural_elements
properties_sed_interpretations_other_fluvial_element
properties_sed_structures_mud_silt_prin_struct
properties_sed_structures_sandstone_struct_notes
properties_sed_structures_faunal_assemblage
properties_sed_strat_section_other_purpose
properties_sed_structures_addl_mud_silt_struct
properties_metamorphic
properties_sed_structures_cement_texture
properties_sed_structures_other_cement_texture
properties_sed_structures_other_addl_mud_silt_struct
properties_sed_structures_other_addl_sandstone_struct
properties_sed_structures_diversity
properties_sed_structures_behavioral_grouping
properties_sed_structures_list_of_specific_types

In [36]:
def find_purpose(spot, purpose_features, purpose_threshold = 2):
    # print(spot)
    features_sum = 0
    not_features_sum = 0
    # not_gm_features = [f for f in spot.index if f not in gm_features]
        
    for feature in spot.index:
        if spot[feature] == 1 and feature in purpose_features:
            features_sum += 1
        elif spot[feature] == 1 and feature not in purpose_features:
            not_features_sum += 1
            
    purpose_presence = features_sum
    not_purpose_presence = not_features_sum
    
    # if no features that are not a part of the purpose are present, assume spot is the purpose
    if not_purpose_presence == 0:
        return True
    
    if purpose_presence / not_purpose_presence >= purpose_threshold: 
        return True
    else:
        return False

In [37]:
df_copy = df.copy()

In [38]:
gm_features = ["properties_rock_unit_unit_label_abbreviation",
               "properties_images_notes",
               "properties_images",
               "properties_notes",
               "properties_pet_rock_type",
               "geometry_coordinates",
               "properties_images"
               "properties_orientation_data", 
               "properties_trace_trace_feature", 
               "properties_trace_trace_quality", 
               "properties_trace_trace_type", 
               "properties_trace_contact_type", 
               "properties_other_features"
               ]

site_safety_features = ["properties_site_safety_site_summary_author",
                        "properties_site_safety_field_stop_designation",
                        "properties_site_safety_longitude",
                        "properties_site_safety_latitude"
                        ]

strat_features = [ "properties_sed_strat_section_column_profile",
                  "properties_sed_strat_section_column_y_axis_units",
                  "properties_sed_strat_section_purpose",
                  "properties_sed_strat_section_scale_of_interest",
                  "properties_sed_strat_section_obs_interval_bed_obs_scale",
                  "properties_sed_strat_section_section_type",
                  "properties_sed_strat_section_basin",
                  "properties_sed_strat_section_age",
                  "properties_sed_strat_section_total_core_length",
                  "properties_sed_strat_section_images",
                  "properties_sed_strat_section_section_well_name",
                  "properties_sed_strat_section_location_locality",
                  "properties_sed_strat_section_dates_of_work",
                  "properties_sed_strat_section_strat_section_notes",
                  "properties_sed_strat_section_display_lithology_patterns",
                  "properties_sed_strat_section_project_description",
                  "properties_sed_strat_section_how_is_section_georeferenced",
                  "properties_sed_strat_section_misc_labels",
                  "properties_sed_strat_section_what_core_repository",
                  "properties_sed_strat_section_type_of_corer",
                  "properties_sed_strat_section_depth_from_surface_to_start_of",
                  "properties_sed_strat_section_other_purpose",
                  "properties_sed_strat_section_label",
                  "properties_sed_strat_section_other_scale_of_interest"
                  ]

In [39]:
df.shape

(1411385, 433)

In [16]:
# df["is_general_mapping"] = df.apply(lambda x: find_purpose(x,gm_features, purpose_threshold= 1.5), axis = 1)

In [17]:
val_count(df.iloc[:, 440:])

(1416767, 0)

In [18]:
# gm_ids = df[df["is_general_mapping"] == True]["project_id"]

# spots_to_drop = df["project_id"].isin(gm_ids)

# df = df[~spots_to_drop]

In [19]:
df.shape

(1416767, 436)

In [20]:
# df.drop(df[df["is_general_mapping"] == True].index, inplace= True)
# df = df.drop("project_id", axis = 1)
# df = df.drop("is_general_mapping", axis= 1)
# print(df.shape)

In [21]:
df.to_csv("../data/parquets/processed_parquet.csv", index = False)