In [67]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import matplotlib as plt
import numpy as np

In [68]:
df = pd.read_csv("../data/DBScan/dbscan_clustered_0.15.csv")
df.shape

(1229374, 442)

In [69]:
cluster_modes = df[df['cluster_labels'] != -1].groupby('cluster_labels').agg(pd.Series.mode) # gets the mode of every value, similar to a centriod of kmodes 
cluster_means = df[df['cluster_labels'] != -1].groupby('cluster_labels').mean() #gets the prevalence of a feature per cluster
cluster_amount = len(set(df[df['cluster_labels'] != -1]["cluster_labels"]))
print("shape: ", df[df["cluster_labels"] != -1].shape)
print("number of clusters: ", cluster_amount)

shape:  (1213083, 442)
number of clusters:  24

In [70]:
cluster_modes.iloc[:,:5]

,properties_images,properties_notes,properties_orientation_data,properties_name,geometry_type
cluster_labels,,,,,
0,0.0,0.0,0.0,1.0,1.0
1,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,1.0,1.0
3,0.0,1.0,1.0,1.0,1.0
4,0.0,0.0,0.0,1.0,1.0
5,0.0,0.0,1.0,1.0,1.0
6,0.0,0.0,0.0,1.0,1.0
7,0.0,1.0,0.0,1.0,1.0
8,0.0,0.0,1.0,1.0,1.0
9,0.0,0.0,1.0,1.0,1.0
10,0.0,0.0,0.0,1.0,1.0
11,0.0,0.0,0.0,1.0,1.0
12,0.0,0.0,0.0,1.0,1.0
13,0.0,0.0,0.0,1.0,1.0
14,0.0,0.0,0.0,1.0,1.0
15,0.0,0.0,0.0,1.0,1.0
16,0.0,0.0,0.0,1.0,1.0
17,0.0,1.0,0.0,1.0,1.0
18,0.0,0.0,0.0,1.0,1.0
19,0.0,0.0,0.0,1.0,1.0
20,0.0,1.0,0.0,1.0,1.0
21,0.0,0.0,1.0,1.0,1.0
22,0.0,0.0,0.0,1.0,1.0
23,0.0,0.0,1.0,1.0,1.0

In [71]:
for cluster in cluster_modes.index:
    print(f"Cluster {cluster}: {df[df["cluster_labels"] == cluster].shape}")

Cluster 0: (1125394, 442)
Cluster 1: (12464, 442)
Cluster 2: (1084, 442)
Cluster 3: (6612, 442)
Cluster 4: (2991, 442)
Cluster 5: (9630, 442)
Cluster 6: (1284, 442)
Cluster 7: (1101, 442)
Cluster 8: (6652, 442)
Cluster 9: (16679, 442)
Cluster 10: (1677, 442)
Cluster 11: (3869, 442)
Cluster 12: (994, 442)
Cluster 13: (2697, 442)
Cluster 14: (1552, 442)
Cluster 15: (2582, 442)
Cluster 16: (1620, 442)
Cluster 17: (2307, 442)
Cluster 18: (2445, 442)
Cluster 19: (949, 442)
Cluster 20: (2852, 442)
Cluster 21: (1456, 442)
Cluster 22: (2211, 442)
Cluster 23: (1981, 442)

In [72]:
discriminating_features = []

for col in cluster_modes.columns:
    temp = set()
    for cluster in cluster_modes[col]:
        temp.add(cluster)
        
    if len(temp) > 1:
        discriminating_features.append(col)
       
print("Discriminating Features: ") 
for feature in discriminating_features:
    print(f"\t{feature}")

Discriminating Features:
	properties_notes
	properties_orientation_data
	geometry_type
	geometry_coordinates
	properties_trace_trace_feature
	properties_trace_trace_quality
	properties_trace_trace_type
	properties_trace_contact_type
	properties_trace_intrusive_contact_type
	properties_other_features
	properties_orientation_type
	properties_orientation_strike
	properties_orientation_dip_direction
	properties_orientation_dip
	properties_orientation_label
	properties_orientation_quality
	properties_orientation_feature_type
	properties_trace_other_contact_type
	properties_rock_unit_unit_label_abbreviation
	properties_rock_unit_rock_type
	properties_custom_fields_Station
	properties_custom_fields_STATNUM
	properties_custom_fields_VARIANT
	properties_custom_fields_GENERATION
	properties_custom_fields_UTMX
	properties_custom_fields_UTMY
	properties_custom_fields_OBJECTID
	properties_custom_fields_AREA
	properties_custom_fields_PERIMETER
	properties_custom_fields_GEO_
	properties_custom_fields_GEO_ID
	properties_custom_fields_GEO_TYPE
	properties_custom_fields_GEO_SYM
	properties_custom_fields_GEO_LINK
	properties_custom_fields_CODE
	properties_custom_fields_Colour
	properties_custom_fields_Grouping
	properties_custom_fields_Shape_Leng
	properties_custom_fields_Shape_Area
	properties_custom_fields_PlateID
	properties_custom_fields_Terrane(s)
	properties_custom_fields_GEO_PAT
	properties_custom_fields_GEO_MISC
	properties_custom_fields_Orientatio
	properties_custom_fields_Type
	properties_custom_fields_MapUnit
	properties_custom_fields_layer
	properties_custom_fields_path
	properties_custom_fields_fid
	properties_custom_fields_ELEV
	properties_custom_fields_GFP_TYPE
	properties_custom_fields_quality
	properties_custom_fields_type
	properties_custom_fields_UNITLABEL
	properties_custom_fields_ID_FUENTE
	properties_rock_unit_era
	properties_rock_unit_period
	properties_rock_unit_epoch
	properties_rock_unit_group_unit_type
	properties_custom_fields_rock_type
	properties_custom_fields_rock_class
	properties_custom_fields_TYPE
	properties_custom_fields_gid
	properties_custom_fields_state
	properties_custom_fields_county

In [73]:
print(cluster_means[discriminating_features])

                properties_notes  properties_orientation_data  geometry_type  \
cluster_labels
0                       0.205616                     0.298410            1.0
1                       0.039554                     0.411666            0.0
2                       0.042435                     0.023985            1.0
3                       1.000000                     1.000000            1.0
4                       0.000000                     0.000000            1.0
5                       0.007061                     1.000000            1.0
6                       0.145639                     0.158879            1.0
7                       0.998183                     0.000000            1.0
8                       0.079675                     1.000000            1.0
9                       0.175550                     1.000000            1.0
10                      0.395349                     0.000000            1.0
11                      0.000000                     0.000000            1.0
12                      0.000000                     0.000000            1.0
13                      0.339637                     0.000000            1.0
14                      0.209407                     0.000000            1.0
15                      0.425252                     0.000000            1.0
16                      0.000000                     0.000000            1.0
17                      1.000000                     0.000000            1.0
18                      0.053579                     0.000000            1.0
19                      0.000000                     0.000000            1.0
20                      0.549439                     0.000000            1.0
21                      0.000000                     1.000000            1.0
22                      0.061511                     0.000000            1.0
23                      0.019687                     0.994952            1.0

                geometry_coordinates  properties_trace_trace_feature  \
cluster_labels
0                                1.0                        0.034623
1                                0.0                        0.000000
2                                1.0                        0.000000
3                                1.0                        0.000000
4                                1.0                        0.000000
5                                1.0                        0.000000
6                                1.0                        0.000000
7                                1.0                        0.000000
8                                1.0                        0.000000
9                                1.0                        0.000000
10                               1.0                        0.000000
11                               1.0                        0.000000
12                               1.0                        0.000000
13                               1.0                        0.000000
14                               1.0                        0.000000
15                               1.0                        0.000000
16                               1.0                        0.000000
17                               1.0                        0.000000
18                               1.0                        1.000000
19                               1.0                        1.000000
20                               1.0                        0.000000
21                               1.0                        0.000000
22                               1.0                        1.000000
23                               1.0                        0.000000

                properties_trace_trace_quality  properties_trace_trace_type  \
cluster_labels
0                                     0.027351                     0.034195
1                                     0.000000                     0.000000
2                                     0.000000                     0.000000
3                                     0.000000                     0.000000
4                                     0.000000                     0.000000
5                                     0.000000                     0.000000
6                                     0.000000                     0.000000
7                                     0.000000                     0.000000
8                                     0.000000                     0.000000
9                                     0.000000                     0.000000
10                                    0.000000                     0.000000
11                                    0.000000                     0.000000
12                                    0.000000                     0.000000
13                                    0.000000                     0.000000
14                                    0.000000                     0.000000
15                                    0.000000                     0.000000
16                                    0.000000                     0.000000
17                                    0.000000                     0.000000
18                                    1.000000                     1.000000
19                                    1.000000                     1.000000
20                                    0.000000                     0.000000
21                                    0.000000                     0.000000
22                                    0.000000                     1.000000
23                                    0.000000                     0.000000

                properties_trace_contact_type  \
cluster_labels
0                                    0.008342
1                                    0.000000
2                                    0.000000
3                                    0.000000
4                                    0.000000
5                                    0.000000
6                                    0.000000
7                                    0.000000
8                                    0.000000
9                                    0.000000
10                                   0.000000
11                                   0.000000
12                                   0.000000
13                                   0.000000
14                                   0.000000
15                                   0.000000
16                                   0.000000
17                                   0.000000
18                                   0.974233
19                                   1.000000
20                                   0.000000
21                                   0.000000
22                                   1.000000
23                                   0.000000

                properties_trace_intrusive_contact_type  \
cluster_labels
0                                              0.000584
1                                              0.000000
2                                              0.000000
3                                              0.000000
4                                              0.000000
5                                              0.000000
6                                              0.000000
7                                              0.000000
8                                              0.000000
9                                              0.000000
10                                             0.000000
11                                             0.000000
12                                             0.000000
13                                             0.000000
14                                             0.000000
15                                             0.000000
16                                             0.000000
17                                             0.000000
18                                             0.974233
19                                             1.000000
20                                             0.000000
21                                             0.000000
22                                             0.000000
23                                             0.000000

                properties_other_features  ...  properties_rock_unit_era  \
cluster_labels                             ...
0                                0.068597  ...                       0.0
1                                0.276075  ...                       0.0
2                                0.000000  ...                       0.0
3                                0.999849  ...                       0.0
4                                0.000000  ...                       0.0
5                                0.000000  ...                       0.0
6                                0.149533  ...                       0.0
7                                0.000000  ...                       0.0
8                                0.000000  ...                       0.0
9                                0.000000  ...                       0.0
10                               0.000000  ...                       0.0
11                               0.000000  ...                       0.0
12                               0.996982  ...                       0.0
13                               0.000000  ...                       1.0
14                               0.000000  ...                       1.0
15                               0.000000  ...                       0.0
16                               0.000000  ...                       0.0
17                               0.000000  ...                       0.0
18                               0.000000  ...                       0.0
19                               0.000000  ...                       0.0
20                               0.000000  ...                       1.0
21                               0.000000  ...                       0.0
22                               0.000000  ...                       0.0
23                               0.000000  ...                       0.0

                properties_rock_unit_period  properties_rock_unit_epoch  \
cluster_labels
0                                       0.0                         0.0
1                                       0.0                         0.0
2                                       0.0                         0.0
3                                       0.0                         0.0
4                                       0.0                         0.0
5                                       0.0                         0.0
6                                       0.0                         0.0
7                                       0.0                         0.0
8                                       0.0                         0.0
9                                       0.0                         0.0
10                                      0.0                         0.0
11                                      0.0                         0.0
12                                      0.0                         0.0
13                                      1.0                         1.0
14                                      1.0                         0.0
15                                      0.0                         0.0
16                                      0.0                         0.0
17                                      0.0                         0.0
18                                      0.0                         0.0
19                                      0.0                         0.0
20                                      1.0                         1.0
21                                      0.0                         0.0
22                                      0.0                         0.0
23                                      0.0                         0.0

                properties_rock_unit_group_unit_type  \
cluster_labels
0                                                0.0
1                                                0.0
2                                                0.0
3                                                0.0
4                                                0.0
5                                                0.0
6                                                0.0
7                                                0.0
8                                                0.0
9                                                0.0
10                                               0.0
11                                               0.0
12                                               0.0
13                                               1.0
14                                               1.0
15                                               0.0
16                                               0.0
17                                               0.0
18                                               0.0
19                                               0.0
20                                               0.0
21                                               0.0
22                                               0.0
23                                               0.0

                properties_custom_fields_rock_type  \
cluster_labels
0                                              0.0
1                                              0.0
2                                              0.0
3                                              0.0
4                                              0.0
5                                              0.0
6                                              0.0
7                                              0.0
8                                              0.0
9                                              0.0
10                                             0.0
11                                             0.0
12                                             0.0
13                                             0.0
14                                             0.0
15                                             1.0
16                                             0.0
17                                             0.0
18                                             0.0
19                                             0.0
20                                             0.0
21                                             0.0
22                                             0.0
23                                             0.0

                properties_custom_fields_rock_class  \
cluster_labels
0                                               0.0
1                                               0.0
2                                               0.0
3                                               0.0
4                                               0.0
5                                               0.0
6                                               0.0
7                                               0.0
8                                               0.0
9                                               0.0
10                                              0.0
11                                              0.0
12                                              0.0
13                                              0.0
14                                              0.0
15                                              1.0
16                                              0.0
17                                              0.0
18                                              0.0
19                                              0.0
20                                              0.0
21                                              0.0
22                                              0.0
23                                              0.0

                properties_custom_fields_TYPE  properties_custom_fields_gid  \
cluster_labels
0                                         0.0                           0.0
1                                         0.0                           0.0
2                                         0.0                           0.0
3                                         0.0                           0.0
4                                         0.0                           0.0
5                                         0.0                           0.0
6                                         0.0                           0.0
7                                         0.0                           0.0
8                                         0.0                           0.0
9                                         0.0                           0.0
10                                        0.0                           0.0
11                                        0.0                           0.0
12                                        0.0                           0.0
13                                        0.0                           0.0
14                                        0.0                           0.0
15                                        0.0                           0.0
16                                        1.0                           0.0
17                                        0.0                           1.0
18                                        0.0                           0.0
19                                        0.0                           0.0
20                                        0.0                           0.0
21                                        0.0                           0.0
22                                        0.0                           0.0
23                                        0.0                           0.0

                properties_custom_fields_state  \
cluster_labels
0                                          0.0
1                                          0.0
2                                          0.0
3                                          0.0
4                                          0.0
5                                          0.0
6                                          0.0
7                                          0.0
8                                          0.0
9                                          0.0
10                                         0.0
11                                         0.0
12                                         0.0
13                                         0.0
14                                         0.0
15                                         0.0
16                                         0.0
17                                         1.0
18                                         0.0
19                                         0.0
20                                         0.0
21                                         0.0
22                                         0.0
23                                         0.0

                properties_custom_fields_county
cluster_labels
0                                           0.0
1                                           0.0
2                                           0.0
3                                           0.0
4                                           0.0
5                                           0.0
6                                           0.0
7                                           0.0
8                                           0.0
9                                           0.0
10                                          0.0
11                                          0.0
12                                          0.0
13                                          0.0
14                                          0.0
15                                          0.0
16                                          0.0
17                                          1.0
18                                          0.0
19                                          0.0

In [74]:
global_mean = df[df['cluster_labels'] != -1].drop(columns='cluster_labels').mean() # presence in the entire dataset
deviation = cluster_means[discriminating_features] / global_mean[discriminating_features]

deviation

,properties_notes,properties_orientation_data,geometry_type,geometry_coordinates,properties_trace_trace_feature,properties_trace_trace_quality,properties_trace_trace_type,properties_trace_contact_type,properties_trace_intrusive_contact_type,properties_other_features,...,properties_rock_unit_era,properties_rock_unit_period,properties_rock_unit_epoch,properties_rock_unit_group_unit_type,properties_custom_fields_rock_type,properties_custom_fields_rock_class,properties_custom_fields_TYPE,properties_custom_fields_gid,properties_custom_fields_state,properties_custom_fields_county
cluster_labels,,,,,,,,,,,,,,,,,,,,,
0,0.995551,0.942232,1.010381,1.010381,0.942362,0.970868,0.940880,0.677796,0.177581,0.940976,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.191512,1.299837,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.787028,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.205464,0.075734,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4.841796,3.157508,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,13.715308,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.034189,3.157508,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.705153,0.501660,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,2.051197,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,4.833001,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.385771,3.157508,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.849978,3.157508,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,1.914199,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,13.675982,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,1.644451,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,170.8327,170.8327,218.612903,285.49847,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,1.013907,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,170.8327,170.8327,0.000000,285.49847,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,2.058982,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,469.823005,469.823005,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,748.816667,0.000000,0.000000,0.000000
17,4.841796,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,525.827048,525.827048,525.827048
18,0.259417,0.000000,1.010381,1.010381,27.217478,35.496211,27.515038,79.157779,296.345448,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,1.010381,1.010381,27.217478,35.496211,27.515038,81.251373,304.183300,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,2.660272,0.000000,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,170.8327,170.8327,218.612903,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,0.000000,3.157508,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.297822,0.000000,1.010381,1.010381,27.217478,0.000000,27.515038,81.251373,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.095321,3.141569,1.010381,1.010381,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0000,0.0000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [75]:
significant_deviations = {}
cluster_defining_features = {}

for cluster in deviation.index:
    features = deviation.loc[cluster]
    significant = features[features >= 2].sort_values(ascending=False)
    significant_deviations[cluster] = significant

for cluster, features in significant_deviations.items():
    print(f"\nCluster {cluster} : {df[df["cluster_labels"] == cluster].shape[0]} samples")
    if len(features) == 0:
        print("\tNo significant features")
        cluster_defining_features[cluster] = []
    else:
        temp = []
        for feature, ratio in features.items():
            # print(f"\t{feature}: {ratio:.2f}x more present in cluster")
            print(f"\t{feature}")
            temp.append(feature)
        cluster_defining_features[cluster] = temp

Cluster 0 : 1125394 samples
	No significant features

Cluster 1 : 12464 samples
	properties_other_features

Cluster 2 : 1084 samples
	properties_orientation_feature_type
	properties_orientation_type
	properties_orientation_strike
	properties_orientation_dip_direction
	properties_orientation_dip
	properties_orientation_label
	properties_orientation_quality

Cluster 3 : 6612 samples
	properties_custom_fields_Station
	properties_custom_fields_STATNUM
	properties_custom_fields_VARIANT
	properties_custom_fields_GENERATION
	properties_custom_fields_UTMX
	properties_custom_fields_UTMY
	properties_other_features
	properties_notes
	properties_orientation_data

Cluster 4 : 2991 samples
	properties_custom_fields_GEO_MISC
	properties_custom_fields_PlateID
	properties_custom_fields_PERIMETER
	properties_custom_fields_GEO_
	properties_custom_fields_GEO_ID
	properties_custom_fields_GEO_TYPE
	properties_custom_fields_GEO_SYM
	properties_custom_fields_GEO_LINK
	properties_custom_fields_GEO_PAT
	properties_custom_fields_Colour
	properties_custom_fields_Grouping
	properties_custom_fields_Terrane(s)
	properties_custom_fields_CODE
	properties_custom_fields_Shape_Area
	properties_custom_fields_AREA
	properties_custom_fields_OBJECTID
	properties_custom_fields_Shape_Leng

Cluster 5 : 9630 samples
	properties_custom_fields_Orientatio
	properties_custom_fields_Type
	properties_custom_fields_MapUnit
	properties_orientation_data

Cluster 6 : 1284 samples
	properties_custom_fields_layer
	properties_custom_fields_path
	properties_other_features

Cluster 7 : 1101 samples
	properties_custom_fields_GFP_TYPE
	properties_notes

Cluster 8 : 6652 samples
	properties_custom_fields_type
	properties_custom_fields_quality
	properties_custom_fields_OBJECTID
	properties_custom_fields_Shape_Leng
	properties_orientation_data

Cluster 9 : 16679 samples
	properties_custom_fields_quality
	properties_custom_fields_OBJECTID
	properties_custom_fields_Shape_Leng
	properties_orientation_data

Cluster 10 : 1677 samples
	properties_custom_fields_UNITLABEL
	properties_custom_fields_Shape_Area

Cluster 11 : 3869 samples
	properties_custom_fields_ID_FUENTE

Cluster 12 : 994 samples
	properties_custom_fields_fid
	properties_other_features

Cluster 13 : 2697 samples
	properties_rock_unit_group_unit_type
	properties_rock_unit_epoch
	properties_rock_unit_rock_type
	properties_rock_unit_era
	properties_rock_unit_period
	properties_rock_unit_unit_label_abbreviation

Cluster 14 : 1552 samples
	properties_rock_unit_group_unit_type
	properties_rock_unit_rock_type
	properties_rock_unit_era
	properties_rock_unit_period
	properties_rock_unit_unit_label_abbreviation

Cluster 15 : 2582 samples
	properties_custom_fields_rock_type
	properties_custom_fields_rock_class
	properties_notes

Cluster 16 : 1620 samples
	properties_custom_fields_TYPE

Cluster 17 : 2307 samples
	properties_custom_fields_gid
	properties_custom_fields_state
	properties_custom_fields_county
	properties_notes

Cluster 18 : 2445 samples
	properties_trace_intrusive_contact_type
	properties_custom_fields_type
	properties_trace_contact_type
	properties_custom_fields_quality
	properties_trace_trace_quality
	properties_trace_trace_type
	properties_trace_trace_feature

Cluster 19 : 949 samples
	properties_trace_intrusive_contact_type
	properties_custom_fields_type
	properties_trace_contact_type
	properties_trace_trace_quality
	properties_trace_trace_type
	properties_trace_trace_feature

Cluster 20 : 2852 samples
	properties_rock_unit_epoch
	properties_rock_unit_era
	properties_rock_unit_period
	properties_rock_unit_rock_type
	properties_rock_unit_unit_label_abbreviation
	properties_notes

Cluster 21 : 1456 samples
	properties_custom_fields_ELEV
	properties_custom_fields_Shape_Leng
	properties_orientation_data

Cluster 22 : 2211 samples
	properties_trace_other_contact_type
	properties_trace_contact_type
	properties_custom_fields_quality
	properties_trace_trace_type
	properties_trace_trace_feature

Cluster 23 : 1981 samples
	properties_custom_fields_quality
	properties_orientation_data

In [76]:
deviation[deviation.index == 0]

,properties_notes,properties_orientation_data,geometry_type,geometry_coordinates,properties_trace_trace_feature,properties_trace_trace_quality,properties_trace_trace_type,properties_trace_contact_type,properties_trace_intrusive_contact_type,properties_other_features,...,properties_rock_unit_era,properties_rock_unit_period,properties_rock_unit_epoch,properties_rock_unit_group_unit_type,properties_custom_fields_rock_type,properties_custom_fields_rock_class,properties_custom_fields_TYPE,properties_custom_fields_gid,properties_custom_fields_state,properties_custom_fields_county
cluster_labels,,,,,,,,,,,,,,,,,,,,,
0,0.995551,0.942232,1.010381,1.010381,0.942362,0.970868,0.94088,0.677796,0.177581,0.940976,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
def val_count(data):
    counter = 0
    for i in data.columns:
        
        # if i in ["properties_viewed_timestamp" ,"properties_modified_timestamp","properties_symbology_circleColor","properties_id","properties_symbology_lineColor","properties_symbology_lineWidth","properties_symbology_lineDasharray","properties_sed_strat_section_strat_section_id","properties_strat_section_id","properties_symbology_fillColor","properties_orientation_id","properties_custom_fields_osm_id","properties_orientation_modified_timestamp","properties_custom_fields_id","properties_orientation_unix_timestamp","properties_gps_accuracy","properties_altitude","properties_notesTimestamp"]: 
        
        print(counter)
        print(data[i].value_counts())
        counter += 1
        print("=========================="*5)
    print(data.shape)
    
val_count(df = df[df["cluster_labels"] == 3])

0
properties_images
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
1
properties_notes
1.0    6612
Name: count, dtype: int64
==================================================================================================================================
2
properties_orientation_data
1.0    6612
Name: count, dtype: int64
==================================================================================================================================
3
properties_name
1.0    6612
Name: count, dtype: int64
==================================================================================================================================
4
geometry_type
1.0    6612
Name: count, dtype: int64
==================================================================================================================================
5
geometry_coordinates
1.0    6612
Name: count, dtype: int64
==================================================================================================================================
6
properties_samples
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
7
properties_altitude_accuracy
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
8
properties_lng
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
9
properties_image_basemap
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
10
properties_lat
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
11
properties__3d_structures
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
12
properties_trace_trace_feature
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
13
properties_trace_trace_quality
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
14
properties_trace_trace_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
15
properties_trace_contact_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
16
properties_trace_intrusive_contact_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
17
properties_trace_metamorphic_contact_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
18
properties_trace_trace_character
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
19
properties_spot_radius
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
20
properties_images_notes
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
21
properties_sed_strat_section_column_profile
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
22
properties_sed_strat_section_column_y_axis_units
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
23
properties_sed_strat_section_purpose
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
24
properties_sed_strat_section_scale_of_interest
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
25
properties_sed_strat_section_obs_interval_bed_obs_scale
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
26
properties_sed_strat_section_section_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
27
properties_sed_strat_section_basin
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
28
properties_sed_strat_section_age
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
29
properties_sed_character
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
30
properties_sed_interval_interval_thickness
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
31
properties_sed_interval_thickness_units
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
32
properties_surface_feature_surface_feature_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
33
properties_sed_lithologies
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
34
properties_sed_strat_section_total_core_length
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
35
properties_sed_bedding_beds
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
36
geometry_geometries
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
37
properties_sed_bedding_interbed_proportion_change
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
38
properties_sed_bedding_interbed_proportion
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
39
properties_sed_bedding_lithology_at_bottom_contact
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
40
properties_sed_bedding_lithology_at_top_contact
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
41
properties_sed_bedding_package_thickness_units
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
42
properties_sed_strat_section_images
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
43
properties_other_features
1.0    6611
0.0       1
Name: count, dtype: int64
==================================================================================================================================
44
properties_tephra
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
45
properties_trace_depositional_contact_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
46
properties_trace_tace_notes
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
47
properties_trace_geologic_structure_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
48
properties_trace_other_feature
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
49
properties_trace_other_other_feature
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
50
properties_sed_fossils
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
51
properties_trace_shear_sense
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
52
properties_trace_geomorphic_feature
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
53
properties_trace_associated_geomorphic_feature
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
54
properties_trace_landscape_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
55
properties_trace_feature_origin
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
56
properties_trace_other_structural_zones
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
57
properties_trace_other_other_structural_zone
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
58
properties_trace_other_geomorphic_feature
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
59
properties_trace_other_shear_sense
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
60
properties_orientation_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
61
properties_orientation_strike
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
62
properties_orientation_dip_direction
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
63
properties_orientation_dip
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
64
properties_orientation_label
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
65
properties_orientation_quality
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
66
properties_orientation_feature_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
67
properties_pet_rock_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
68
properties_pet_igneous_rock_class
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
69
properties_pet_volcanic_rock_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
70
properties_pet_occurence_volcanic
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
71
properties_trace_other_contact_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
72
properties_trace_antropogenic_feature
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
73
properties_trace_other_anthropogenic_feature
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
74
properties_surface_feature_other_surface_feature_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
75
properties_trace_other_depositional_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
76
properties_custom_fields_MIN_AGE
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
77
properties_custom_fields_MAX_AGE
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
78
properties_trace_fold_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
79
properties_trace_fold_attitude
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
80
properties_rock_unit_unit_label_abbreviation
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
81
properties_pet_metamorphic_rock_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
82
properties_sed_bedding_package_bedding_trends
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
83
properties_sed_structures
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
84
properties_sed_interpretations
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
85
properties_pet_protolith
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
86
properties_pet_texture_volcanic
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
87
properties_pet_alteration_volcanic
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
88
properties_trace_other_trace_quality
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
89
properties_sed_strat_section_section_well_name
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
90
properties_sed_strat_section_location_locality
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
91
properties_sed_strat_section_dates_of_work
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
92
properties_sed_strat_section_strat_section_notes
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
93
properties_pet_plutonic_rock_type
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
94
properties_pet_occurence_plutonic
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
95
properties_pet_texture_plutonic
0.0    6612
Name: count, dtype: int64
==================================================================================================================================
96
properties_pet_minerals
0.0    6612
Name: count, dtype: int64
==================================================================================================================================