In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import seaborn as sns

In [40]:
df = pd.read_csv("../data/dbscan_clustered_parquet.csv")
df.shape

(1359345, 441)

In [ ]:
cluster_modes = df[df['cluster_labels'] != -1].groupby('cluster_labels').agg(pd.Series.mode) # gets the mode of every value, similar to a centriod of kmodes 
cluster_means = df[df['cluster_labels'] != -1].groupby('cluster_labels').mean() #gets the prevalence of a feature per cluster
df[df["cluster_labels"] != -1].shape

(1359224, 441)

In [42]:
cluster_modes.iloc[:,:441]

,properties_images,properties_notes,properties_orientation_data,properties_name,properties_notesTimestamp,geometry_type,geometry_coordinates,properties_samples,properties_altitude_accuracy,properties_lng,...,properties_custom_fields_ID,properties_custom_fields_LITOLOGIA,properties_physical,properties_custom_fields_TIPO,properties_custom_fields_NOME,properties_sed_lithologies_sandstone_modifier,properties_sed_lithologies_shape_of_upper_contacts,properties_sed_structures_trough_height,properties_sed_strat_section_other_scale_of_interest,properties_sed_lithologies_gypsum_anhydrite_diagenetic_percent
cluster_labels,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [58]:
for cluster in cluster_modes.index:
    print(f"Cluster {cluster}: {df[df["cluster_labels"] == cluster].shape}")

Cluster 0: (1356120, 441)
Cluster 1: (3104, 441)

In [50]:
discriminating_features = []

for col in cluster_modes.columns:
    temp = set()
    for cluster in cluster_modes[col]:
        temp.add(cluster)
        
    if len(temp) > 1:
        discriminating_features.append(col)
       
print("Discriminating Features: ") 
for feature in discriminating_features:
    print(f"\t{feature}")

Discriminating Features:
	properties_custom_fields_OBJECTID
	properties_custom_fields_AREA
	properties_custom_fields_PERIMETER
	properties_custom_fields_GEO_
	properties_custom_fields_GEO_ID
	properties_custom_fields_GEO_TYPE
	properties_custom_fields_GEO_SYM
	properties_custom_fields_GEO_LINK
	properties_custom_fields_CODE
	properties_custom_fields_Colour
	properties_custom_fields_Grouping
	properties_custom_fields_Shape_Leng
	properties_custom_fields_Shape_Area
	properties_custom_fields_PlateID
	properties_custom_fields_Terrane(s)
	properties_custom_fields_GEO_PAT
	properties_custom_fields_GEO_MISC

In [51]:
print(cluster_means[discriminating_features])

                properties_custom_fields_OBJECTID  \
cluster_labels
0                                        0.028567
1                                        1.000000

                properties_custom_fields_AREA  \
cluster_labels
0                                    0.007957
1                                    1.000000

                properties_custom_fields_PERIMETER  \
cluster_labels
0                                              0.0
1                                              1.0

                properties_custom_fields_GEO_  \
cluster_labels
0                                         0.0
1                                         1.0

                properties_custom_fields_GEO_ID  \
cluster_labels
0                                           0.0
1                                           1.0

                properties_custom_fields_GEO_TYPE  \
cluster_labels
0                                             0.0
1                                             1.0

                properties_custom_fields_GEO_SYM  \
cluster_labels
0                                            0.0
1                                            1.0

                properties_custom_fields_GEO_LINK  \
cluster_labels
0                                             0.0
1                                             1.0

                properties_custom_fields_CODE  \
cluster_labels
0                                    0.000058
1                                    1.000000

                properties_custom_fields_Colour  \
cluster_labels
0                                           0.0
1                                           1.0

                properties_custom_fields_Grouping  \
cluster_labels
0                                             0.0
1                                             1.0

                properties_custom_fields_Shape_Leng  \
cluster_labels
0                                          0.029244
1                                          1.000000

                properties_custom_fields_Shape_Area  \
cluster_labels
0                                          0.005654
1                                          1.000000

                properties_custom_fields_PlateID  \
cluster_labels
0                                       0.000000
1                                       0.963595

                properties_custom_fields_Terrane(s)  \
cluster_labels
0                                          0.000000
1                                          0.963595

                properties_custom_fields_GEO_PAT  \
cluster_labels
0                                       0.000000
1                                       0.511276

                properties_custom_fields_GEO_MISC
cluster_labels
0                                        0.000000
1                                        0.526418

In [45]:
global_mean = df[df['cluster_labels'] != -1].drop(columns='cluster_labels').mean()
deviation = cluster_means - global_mean

deviation

,properties_images,properties_notes,properties_orientation_data,properties_name,properties_notesTimestamp,geometry_type,geometry_coordinates,properties_samples,properties_altitude_accuracy,properties_lng,...,properties_custom_fields_ID,properties_custom_fields_LITOLOGIA,properties_physical,properties_custom_fields_TIPO,properties_custom_fields_NOME,properties_sed_lithologies_sandstone_modifier,properties_sed_lithologies_shape_of_upper_contacts,properties_sed_structures_trough_height,properties_sed_strat_section_other_scale_of_interest,properties_sed_lithologies_gypsum_anhydrite_diagenetic_percent
cluster_labels,,,,,,,,,,,,,,,,,,,,,
0,0.000347,0.000538,0.000652,-0.000006,0.000197,-0.000022,-0.000024,0.000052,0.000034,0.000042,...,8.436655e-07,1.010378e-08,1.683963e-09,9.581750e-07,8.419815e-09,0.0,1.683963e-09,1.683963e-09,3.367926e-09,1.683963e-09
1,-0.151779,-0.235239,-0.284806,0.002683,-0.086228,0.009678,0.010463,-0.022684,-0.015071,-0.018497,...,-3.685927e-04,-4.414283e-06,-7.357139e-07,-4.186212e-04,-3.678570e-06,0.0,-7.357139e-07,-7.357139e-07,-1.471428e-06,-7.357139e-07